// flow-typed signature: 3b00635363cab7d870dea3bac809b73b
// flow-typed version: <<STUB>>/eslint-module-utils_v^2.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-module-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-module-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-module-utils/declaredScope' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/hash' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/ignore' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/module-require' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/ModuleCache' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/moduleVisitor' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/parse' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/resolve' {
  declare module.exports: any;
}

declare module 'eslint-module-utils/unambiguous' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-module-utils/declaredScope.js' {
  declare module.exports: $Exports<'eslint-module-utils/declaredScope'>;
}
declare module 'eslint-module-utils/hash.js' {
  declare module.exports: $Exports<'eslint-module-utils/hash'>;
}
declare module 'eslint-module-utils/ignore.js' {
  declare module.exports: $Exports<'eslint-module-utils/ignore'>;
}
declare module 'eslint-module-utils/module-require.js' {
  declare module.exports: $Exports<'eslint-module-utils/module-require'>;
}
declare module 'eslint-module-utils/ModuleCache.js' {
  declare module.exports: $Exports<'eslint-module-utils/ModuleCache'>;
}
declare module 'eslint-module-utils/moduleVisitor.js' {
  declare module.exports: $Exports<'eslint-module-utils/moduleVisitor'>;
}
declare module 'eslint-module-utils/parse.js' {
  declare module.exports: $Exports<'eslint-module-utils/parse'>;
}
declare module 'eslint-module-utils/resolve.js' {
  declare module.exports: $Exports<'eslint-module-utils/resolve'>;
}
declare module 'eslint-module-utils/unambiguous.js' {
  declare module.exports: $Exports<'eslint-module-utils/unambiguous'>;
}
