// flow-typed signature: de62c229601a7e7ed18e5267c0903367
// flow-typed version: <<STUB>>/semantic-release_v^8.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-release/bin/semantic-release' {
  declare module.exports: any;
}

declare module 'semantic-release/src/index' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/get-commits' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/get-registry' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/get-release-type' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/get-version-head' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/plugin-noop' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/plugins' {
  declare module.exports: any;
}

declare module 'semantic-release/src/lib/verify' {
  declare module.exports: any;
}

declare module 'semantic-release/src/post' {
  declare module.exports: any;
}

declare module 'semantic-release/src/pre' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-release/bin/semantic-release.js' {
  declare module.exports: $Exports<'semantic-release/bin/semantic-release'>;
}
declare module 'semantic-release/src/index.js' {
  declare module.exports: $Exports<'semantic-release/src/index'>;
}
declare module 'semantic-release/src/lib/get-commits.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/get-commits'>;
}
declare module 'semantic-release/src/lib/get-registry.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/get-registry'>;
}
declare module 'semantic-release/src/lib/get-release-type.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/get-release-type'>;
}
declare module 'semantic-release/src/lib/get-version-head.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/get-version-head'>;
}
declare module 'semantic-release/src/lib/plugin-noop.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/plugin-noop'>;
}
declare module 'semantic-release/src/lib/plugins.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/plugins'>;
}
declare module 'semantic-release/src/lib/verify.js' {
  declare module.exports: $Exports<'semantic-release/src/lib/verify'>;
}
declare module 'semantic-release/src/post.js' {
  declare module.exports: $Exports<'semantic-release/src/post'>;
}
declare module 'semantic-release/src/pre.js' {
  declare module.exports: $Exports<'semantic-release/src/pre'>;
}
